---
# If users don't set devops.agent.config or
- name: ks-devops | Preparing for default Jenkins agent configuration
  include_vars: vars/jenkins_agent_limit_default.yaml
  when: devops.agent.config is not defined or devops.agent.config == "default"
- name: ks-devops | Preparing for high Jenkins agent configuration
  include_vars: vars/jenkins_agent_limit_high.yaml
  when: devops.agent.config is defined and devops.agent.config == "high"
- name: ks-devops | Debug devops_agent
  debug:
    var: devops_agent
- name: ks-devops | Debug devops_worker
  debug:
    var: devops_worker
