apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ks-jenkins
    app.kubernetes.io/vendor: kubesphere
  name: ks-jenkins
  namespace: kubesphere-monitoring-system
spec:
  endpoints:
  - honorLabels: true
    interval: 1m
    port: http
    path: /prometheus/
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kubesphere-devops-system
  selector:
    matchLabels:
      app: ks-jenkins
